# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks: 
    -   id: isort
        args: [--profile black]
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.2.0
    hooks:
    -   id: autoflake
        args: [--remove-all-unused-imports, --recursive, --remove-unused-variables, --in-place]
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.0'  # version 2.7.1
    hooks:
    -   id: prettier
        types_or: [javascript, html, css, json]
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.44.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: eslint
        additional_dependencies:
        - eslint
        - eslint-config-react-app